name: Build and Test SDChecker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    defaults:
      run:
        working-directory: SDChecker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet packages
      run: dotnet restore SDChecker.sln

    - name: Build with dotnet build (instead of msbuild)
      run: dotnet build SDChecker.sln --configuration ${{ matrix.configuration }} --no-restore

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SDChecker-${{ matrix.configuration }}
        path: SDChecker/SDChecker/bin/${{ matrix.configuration }}
