name: Build and Test SDChecker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    defaults:
      run:
        working-directory: SDChecker/SDChecker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore SDChecker.sln

    - name: Build project
      run: msbuild SDChecker.sln /p:Configuration=${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SDChecker-${{ matrix.configuration }}
        path: SDChecker/SDChecker/bin/${{ matrix.configuration }}
